# Reading csv files

In [4]:
import pandas as pd
df = pd.read_csv("data/stock_data.csv", skiprows=1) # using skipsrows argument to skip the redundant header
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [6]:
df = pd.read_csv("data/stock_data.csv", header=None, names=["tickers","eps","revenue","price","people"]) # Making a header and specifying column names
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [8]:
df = pd.read_csv("data/stock_data.csv", nrows=4) # Reading 4 rows
df

  tickers            eps  revenue  price         people
0   GOOGL          27.82       87    845     larry page
1     WMT           4.61      484     65           n.a.
2    MSFT             -1       85     64     bill gates
3    RIL   not available       50   1023  mukesh ambani

In [9]:
df = pd.read_csv("data/stock_data.csv", na_values=["not available", "n.a."]) # replacing ["not available", "n.a."] with NaN values
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82       87   845.0     larry page
1     WMT   4.61      484    65.0            NaN
2    MSFT  -1.00       85    64.0     bill gates
3    RIL     NaN       50  1023.0  mukesh ambani
4    TATA   5.60       -1     NaN     ratan tata

In [10]:
# Replacing ["not available", "n.a."] and other irrelevant values with NaN
df = pd.read_csv("data/stock_data.csv", na_values = {
    'eps' : ["not available", "n.a."],
    'revenue' : ["not available", "n.a.", "-1"],
    'people' : ["not available", "n.a."],
    'price' : ["not available", "n.a.", "-1"]
})
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT  -1.00     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

# Writing to CSV

In [12]:
df.to_csv("data/new.csv", index=False)

In [19]:
df.to_csv("data/new.csv", columns = ["tickers", "eps"], index=False) # Exporting only the specified colums to new.csv

# Reading Excel files

In [33]:
df = pd.read_excel("data/new.xlsx")
df

   Unnamed: 0 tickers            eps  revenue price         people
0           0   GOOGL          27.82       87   845     larry page
1           1     WMT           4.61      484    65           n.a.
2           2    MSFT             -1       85    64     bill gates
3           3    RIL   not available       50  1023  mukesh ambani
4           4    TATA            5.6       -1  n.a.     ratan tata

In [49]:
# Using "converter=" argument
def convert_people_cell(cell):
    if cell == "n.a.":
        return "Sam Walton"
    return cell

def convert_eps_cell(cell):
    if cell == "not available":
        return None
    return cell
df = pd.read_excel("data/new.xlsx", converters={
    "people" : convert_people_cell,
    "eps" : convert_eps_cell
}, index_col=0)
df

  tickers    eps  revenue price         people
0   GOOGL  27.82       87   845     larry page
1     WMT   4.61      484    65     Sam Walton
2    MSFT     -1       85    64     bill gates
3    RIL    None       50  1023  mukesh ambani
4    TATA    5.6       -1  n.a.     ratan tata

In [51]:
df.to_excel("data/new_converted.xlsx", index=False)
df_converted = pd.read_excel("data/new_converted.xlsx", index_col=0)
df_converted

           eps  revenue price         people
tickers
GOOGL    27.82       87   845     larry page
WMT       4.61      484    65     Sam Walton
MSFT     -1.00       85    64     bill gates
RIL        NaN       50  1023  mukesh ambani
TATA      5.60       -1  n.a.     ratan tata

In [53]:
df.to_excel("data/new_converted.xlsx", index= False, startrow=1, startcol=2, sheet_name="stocks")
df_converted = pd.read_excel("data/new_converted.xlsx", index_col=0)
df_converted

     Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5     Unnamed: 6
NaN         NaN    tickers        eps    revenue      price         people
NaN         NaN      GOOGL      27.82         87        845     larry page
NaN         NaN        WMT       4.61        484         65     Sam Walton
NaN         NaN       MSFT         -1         85         64     bill gates
NaN         NaN       RIL         NaN         50       1023  mukesh ambani
NaN         NaN       TATA        5.6         -1       n.a.     ratan tata

In [57]:
#
df_stocks = pd.read_excel("data/new_converted.xlsx", index_col=0)
df_weather = pd.read_csv("data/weather_by_cities.csv", index_col=0)

with pd.ExcelWriter("data/stocks_weather.xlsx") as writer:
    df_stocks.to_excel(writer, sheet_name="stocks")
    df_weather.to_excel(writer, sheet_name="weather")